# payment-service — платежи, порт 8084, база payments_db.
# Общий шаблон всех семи сервисов описан в gateway.yml.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: iskstep93/payment-service:05
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: my-config
            - secretRef:
                name: my-secrets
          env:
            - name: POSTGRES_DB
              value: payments_db
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - port: 8084
      targetPort: 8084
