{
 "title": "ДО9",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Количество полученных запросов на gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "gateway_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container!=\"\"} | line_format `{{.service_name}} -> {{__line__}}`"
    }
   ]
  },
  {
   "title": "Доступная и занятая память",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\"} - node_filesystem_avail_bytes{mountpoint=\"/\", fstype=\"ext4\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", fstype=\"ext4\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование CPU по сервисам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name) (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name!=\"\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество Нод",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"node_exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество стеков",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (container_label_com_docker_stack_namespace) (container_last_seen{container_label_com_docker_stack_namespace!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://www.google.com\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "затраченная RAM GB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"cAdvisor\"}) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество обработанных сообщений в rabbitmq",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_processed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество отправленных сообщений в rabbitmq",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_sent_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество CPU на ноду",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Использование CPU по ядрам и узлам",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg by (instance) (\n    rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\n  ) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество бронирований",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bookings_counter_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Количество контейнеров",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "sum(swarm_containers_running{job=\"node_exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество полученных запросов на авторизацию пользователей",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "authorization_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}